//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.34209
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiscController {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class lang {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal lang() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DiscController.lang", typeof(lang).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All current tags are in request.
        /// </summary>
        internal static string All_tags_are_active {
            get {
                return ResourceManager.GetString("All_tags_are_active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A tag must be longer than 3 symbols, but shorter than 125 and consist only of large and small latin letters, numbers and &quot;_&quot; symbol..
        /// </summary>
        internal static string ERROR_CHARCHECK {
            get {
                return ResourceManager.GetString("ERROR_CHARCHECK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Did not delete the tag..
        /// </summary>
        internal static string ERROR_DID_NOT_DELETE {
            get {
                return ResourceManager.GetString("ERROR_DID_NOT_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Can&apos;t load from file. The file may be broken. If that is the case, please contact developers with this error:
        ///.
        /// </summary>
        internal static string ERROR_DISC_LOAD {
            get {
                return ResourceManager.GetString("ERROR_DISC_LOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A following error happened when trying to load file:
        ///.
        /// </summary>
        internal static string ERROR_FILE_LOAD {
            get {
                return ResourceManager.GetString("ERROR_FILE_LOAD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The file that you have selected exceeds maximum possible filesize..
        /// </summary>
        internal static string ERROR_FILE_TOO_LARGE {
            get {
                return ResourceManager.GetString("ERROR_FILE_TOO_LARGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Error!.
        /// </summary>
        internal static string ERROR_MESSAGEBOX_HEADER {
            get {
                return ResourceManager.GetString("ERROR_MESSAGEBOX_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This tag is already added to your search..
        /// </summary>
        internal static string ERROR_TAG_ACTIVE {
            get {
                return ResourceManager.GetString("ERROR_TAG_ACTIVE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This tag already exists..
        /// </summary>
        internal static string ERROR_TAG_EXISTS {
            get {
                return ResourceManager.GetString("ERROR_TAG_EXISTS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This tag was not found..
        /// </summary>
        internal static string ERROR_TAG_MISSING {
            get {
                return ResourceManager.GetString("ERROR_TAG_MISSING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Maximum amount of tags reached. .
        /// </summary>
        internal static string ERROR_TOO_MANY_TAGS {
            get {
                return ResourceManager.GetString("ERROR_TOO_MANY_TAGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unknown error during last operation..
        /// </summary>
        internal static string ERROR_UNKNOWN {
            get {
                return ResourceManager.GetString("ERROR_UNKNOWN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tags To Add.
        /// </summary>
        internal static string FileTagAdder_ActiveTagsTab {
            get {
                return ResourceManager.GetString("FileTagAdder_ActiveTagsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Tags and Close.
        /// </summary>
        internal static string FileTagAdder_AddTagsAndCloseButton {
            get {
                return ResourceManager.GetString("FileTagAdder_AddTagsAndCloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на All current tags are already added.
        /// </summary>
        internal static string FileTagAdder_All_Tags_Are_Active {
            get {
                return ResourceManager.GetString("FileTagAdder_All_Tags_Are_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close.
        /// </summary>
        internal static string FileTagAdder_CloseButton {
            get {
                return ResourceManager.GetString("FileTagAdder_CloseButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New Tag.
        /// </summary>
        internal static string FileTagAdder_NewTagButton {
            get {
                return ResourceManager.GetString("FileTagAdder_NewTagButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No tags will be added.
        /// </summary>
        internal static string FileTagAdder_No_Active_Tags {
            get {
                return ResourceManager.GetString("FileTagAdder_No_Active_Tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tags.
        /// </summary>
        internal static string FileTagAdder_TagsTab {
            get {
                return ResourceManager.GetString("FileTagAdder_TagsTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Show Items Per Page:.
        /// </summary>
        internal static string ItemsPerPage {
            get {
                return ResourceManager.GetString("ItemsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Close.
        /// </summary>
        internal static string MENU_0_Close {
            get {
                return ResourceManager.GetString("MENU_0_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Disc.
        /// </summary>
        internal static string MENU_0_Disc {
            get {
                return ResourceManager.GetString("MENU_0_Disc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на New.
        /// </summary>
        internal static string MENU_0_New {
            get {
                return ResourceManager.GetString("MENU_0_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open.
        /// </summary>
        internal static string MENU_0_Open {
            get {
                return ResourceManager.GetString("MENU_0_Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Open Settings.
        /// </summary>
        internal static string MENU_1_OpenSettings {
            get {
                return ResourceManager.GetString("MENU_1_OpenSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        internal static string MENU_1_Settings {
            get {
                return ResourceManager.GetString("MENU_1_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add.
        /// </summary>
        internal static string MENU_2_Add {
            get {
                return ResourceManager.GetString("MENU_2_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File.
        /// </summary>
        internal static string MENU_2_File {
            get {
                return ResourceManager.GetString("MENU_2_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove.
        /// </summary>
        internal static string MENU_2_Remove {
            get {
                return ResourceManager.GetString("MENU_2_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search.
        /// </summary>
        internal static string MENU_2_Search {
            get {
                return ResourceManager.GetString("MENU_2_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add.
        /// </summary>
        internal static string MENU_3_Add {
            get {
                return ResourceManager.GetString("MENU_3_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove.
        /// </summary>
        internal static string MENU_3_Remove {
            get {
                return ResourceManager.GetString("MENU_3_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Search.
        /// </summary>
        internal static string MENU_3_Search {
            get {
                return ResourceManager.GetString("MENU_3_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tag.
        /// </summary>
        internal static string MENU_3_Tag {
            get {
                return ResourceManager.GetString("MENU_3_Tag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About.
        /// </summary>
        internal static string MENU_4_About {
            get {
                return ResourceManager.GetString("MENU_4_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Help.
        /// </summary>
        internal static string MENU_4_Help {
            get {
                return ResourceManager.GetString("MENU_4_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на How to Use.
        /// </summary>
        internal static string MENU_4_HowToUse {
            get {
                return ResourceManager.GetString("MENU_4_HowToUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add Tag.
        /// </summary>
        internal static string NEWTAGADDER_ADD_BUTTON {
            get {
                return ResourceManager.GetString("NEWTAGADDER_ADD_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        internal static string NEWTAGADDER_CANCEL {
            get {
                return ResourceManager.GetString("NEWTAGADDER_CANCEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add New Tag.
        /// </summary>
        internal static string NEWTAGADDER_HEADER {
            get {
                return ResourceManager.GetString("NEWTAGADDER_HEADER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Request is empty.
        /// </summary>
        internal static string NO_ACTIVE_TAGS {
            get {
                return ResourceManager.GetString("NO_ACTIVE_TAGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No tags found.
        /// </summary>
        internal static string NO_TAGS {
            get {
                return ResourceManager.GetString("NO_TAGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add New.
        /// </summary>
        internal static string RMB_CLICK_1_AddNew {
            get {
                return ResourceManager.GetString("RMB_CLICK_1_AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        internal static string RMB_CLICK_1_Delete {
            get {
                return ResourceManager.GetString("RMB_CLICK_1_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Exclude.
        /// </summary>
        internal static string RMB_CLICK_1_Exclude {
            get {
                return ResourceManager.GetString("RMB_CLICK_1_Exclude", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Include.
        /// </summary>
        internal static string RMB_CLICK_1_Include {
            get {
                return ResourceManager.GetString("RMB_CLICK_1_Include", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Change Search Option.
        /// </summary>
        internal static string RMB_CLICK_2_ChangeSearchOption {
            get {
                return ResourceManager.GetString("RMB_CLICK_2_ChangeSearchOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Remove.
        /// </summary>
        internal static string RMB_CLICK_2_Remove {
            get {
                return ResourceManager.GetString("RMB_CLICK_2_Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete.
        /// </summary>
        internal static string RMB_CLICK_3_Delete {
            get {
                return ResourceManager.GetString("RMB_CLICK_3_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Edit Tags.
        /// </summary>
        internal static string RMB_CLICK_3_Edit_tags {
            get {
                return ResourceManager.GetString("RMB_CLICK_3_Edit_tags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Save as.
        /// </summary>
        internal static string RMB_CLICK_3_Save_as {
            get {
                return ResourceManager.GetString("RMB_CLICK_3_Save_as", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Tags.
        /// </summary>
        internal static string Tab1 {
            get {
                return ResourceManager.GetString("Tab1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Request.
        /// </summary>
        internal static string Tab2 {
            get {
                return ResourceManager.GetString("Tab2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на This is not a tag.
        /// </summary>
        internal static string This_is_not_a_tag {
            get {
                return ResourceManager.GetString("This_is_not_a_tag", resourceCulture);
            }
        }
    }
}
